name: Publish on NPM and GPR

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/publish-nuget.yml'
      - 'src/Bannerlord.LauncherManager/**.*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish on NPM and GPR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 10.x

      - run: dotnet pack -c Release src/Bannerlord.LauncherManager.Localization -p:VersionOverride=$(git rev-list --no-merges --count master) -o ./packages
      
      - run: dotnet pack -c Release src/Bannerlord.LauncherManager.Models -p:VersionOverride=$(git rev-list --no-merges --count master) -o ./packages
     
      - run: dotnet pack -c Release src/Bannerlord.LauncherManager -p:VersionOverride=$(git rev-list --no-merges --count master) -o ./packages

      - name: Push to NuGet
        run: dotnet nuget push "./packages/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org --skip-duplicate
        shell: pwsh

      - name: Push to GPR
        run: |
          for f in ./packages/*.nupkg
          do
            curl -vX PUT -u "vslee:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/BUTR/
          done